/**
 * Curated common-foods library.
 *
 * A hand-maintained set of everyday staples with sensible per-100g macros
 * AND natural portion units ("1 large egg", "1 slice", "1 medium banana").
 * Bundled with the app - instant, offline, no API flakiness - and ranked
 * at the top of search so logging the basics is one tap.
 *
 * Open Food Facts (barcodes / packaged) and USDA (broader generic search)
 * stay as secondary online sources for anything not in here.
 *
 * Macros are approximate, sourced from standard UK/US nutrition data, and
 * are per 100 g (or per 100 ml for liquids - close enough at ~1 g/ml).
 *
 * Bump CURATED_VERSION whenever this list changes so installed apps
 * re-seed on next load.
 */

export const CURATED_VERSION = 3;

export interface CuratedUnit {
  label: string;
  grams: number;
}

export interface CuratedFood {
  slug: string;
  name: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  units: CuratedUnit[];
}

export const CURATED_FOODS: CuratedFood[] = [
  // ---- Eggs ----
  {
    slug: 'egg-whole',
    name: 'Egg, whole, raw',
    kcal: 143, protein: 12.6, carbs: 0.7, fat: 9.5,
    units: [
      { label: 'large egg', grams: 50 },
      { label: 'medium egg', grams: 44 },
      { label: 'small egg', grams: 38 },
    ],
  },
  {
    slug: 'egg-white',
    name: 'Egg white, raw',
    kcal: 52, protein: 10.9, carbs: 0.7, fat: 0.2,
    units: [{ label: 'large egg white', grams: 33 }],
  },
  {
    slug: 'egg-fried',
    name: 'Egg, fried',
    kcal: 196, protein: 13.6, carbs: 0.8, fat: 15,
    units: [{ label: 'large egg', grams: 46 }],
  },
  // ---- Bread & grains ----
  {
    slug: 'bread-white',
    name: 'White bread',
    kcal: 265, protein: 9, carbs: 49, fat: 3.2,
    units: [
      { label: 'slice', grams: 36 },
      { label: 'thick slice', grams: 44 },
    ],
  },
  {
    slug: 'bread-wholemeal',
    name: 'Wholemeal bread',
    kcal: 247, protein: 13, carbs: 41, fat: 3.4,
    units: [
      { label: 'slice', grams: 36 },
      { label: 'thick slice', grams: 44 },
    ],
  },
  {
    slug: 'bagel-plain',
    name: 'Bagel, plain',
    kcal: 250, protein: 10, carbs: 48, fat: 1.5,
    units: [{ label: 'bagel', grams: 85 }],
  },
  {
    slug: 'oats-rolled',
    name: 'Rolled oats, dry',
    kcal: 379, protein: 13.2, carbs: 67.7, fat: 6.5,
    units: [
      { label: 'serving', grams: 40 },
      { label: 'cup', grams: 80 },
    ],
  },
  {
    slug: 'rice-white-cooked',
    name: 'White rice, cooked',
    kcal: 130, protein: 2.7, carbs: 28, fat: 0.3,
    units: [
      { label: 'serving', grams: 150 },
      { label: 'cup', grams: 158 },
    ],
  },
  {
    slug: 'pasta-cooked',
    name: 'Pasta, cooked',
    kcal: 158, protein: 5.8, carbs: 31, fat: 0.9,
    units: [
      { label: 'serving', grams: 180 },
      { label: 'cup', grams: 140 },
    ],
  },
  {
    slug: 'potato-boiled',
    name: 'Potato, boiled',
    kcal: 87, protein: 1.9, carbs: 20, fat: 0.1,
    units: [{ label: 'medium potato', grams: 150 }],
  },
  {
    slug: 'sweet-potato-baked',
    name: 'Sweet potato, baked',
    kcal: 90, protein: 2, carbs: 21, fat: 0.15,
    units: [{ label: 'medium', grams: 130 }],
  },
  // ---- Dairy ----
  {
    slug: 'milk-whole',
    name: 'Whole milk',
    kcal: 64, protein: 3.4, carbs: 4.7, fat: 3.6,
    units: [
      { label: 'glass (200ml)', grams: 200 },
      { label: 'splash', grams: 30 },
    ],
  },
  {
    slug: 'milk-semi',
    name: 'Semi-skimmed milk',
    kcal: 50, protein: 3.5, carbs: 4.8, fat: 1.8,
    units: [
      { label: 'glass (200ml)', grams: 200 },
      { label: 'splash', grams: 30 },
    ],
  },
  {
    slug: 'milk-skimmed',
    name: 'Skimmed milk',
    kcal: 35, protein: 3.5, carbs: 5, fat: 0.1,
    units: [{ label: 'glass (200ml)', grams: 200 }],
  },
  {
    slug: 'yogurt-greek',
    name: 'Greek yogurt, plain',
    kcal: 97, protein: 9, carbs: 4, fat: 5,
    units: [
      { label: 'pot (150g)', grams: 150 },
      { label: 'tbsp', grams: 18 },
    ],
  },
  {
    slug: 'yogurt-natural',
    name: 'Natural yogurt',
    kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3,
    units: [{ label: 'pot (150g)', grams: 150 }],
  },
  {
    slug: 'cheese-cheddar',
    name: 'Cheddar cheese',
    kcal: 416, protein: 25, carbs: 0.1, fat: 35,
    units: [
      { label: 'slice', grams: 25 },
      { label: 'matchbox', grams: 30 },
    ],
  },
  {
    slug: 'butter',
    name: 'Butter',
    kcal: 717, protein: 0.85, carbs: 0.06, fat: 81,
    units: [
      { label: 'tsp', grams: 5 },
      { label: 'tbsp', grams: 14 },
    ],
  },
  // ---- Proteins ----
  {
    slug: 'chicken-breast-cooked',
    name: 'Chicken breast, cooked',
    kcal: 165, protein: 31, carbs: 0, fat: 3.6,
    units: [
      { label: 'breast', grams: 120 },
      { label: 'serving', grams: 100 },
    ],
  },
  {
    slug: 'chicken-breast-raw',
    name: 'Chicken breast, raw',
    kcal: 110, protein: 23, carbs: 0, fat: 1.5,
    units: [{ label: 'breast', grams: 150 }],
  },
  {
    slug: 'chicken-thigh-cooked',
    name: 'Chicken thigh, cooked',
    kcal: 209, protein: 26, carbs: 0, fat: 11,
    units: [{ label: 'thigh', grams: 90 }],
  },
  {
    slug: 'beef-mince-5',
    name: 'Beef mince, 5% fat, cooked',
    kcal: 182, protein: 26, carbs: 0, fat: 8,
    units: [{ label: 'serving', grams: 125 }],
  },
  {
    slug: 'salmon-cooked',
    name: 'Salmon, cooked',
    kcal: 206, protein: 22, carbs: 0, fat: 13,
    units: [{ label: 'fillet', grams: 120 }],
  },
  {
    slug: 'tuna-canned',
    name: 'Tuna, canned in brine, drained',
    kcal: 116, protein: 26, carbs: 0, fat: 1,
    units: [{ label: 'can (145g)', grams: 145 }],
  },
  {
    slug: 'prawns-cooked',
    name: 'Prawns, cooked',
    kcal: 99, protein: 24, carbs: 0.2, fat: 0.3,
    units: [{ label: 'serving', grams: 100 }],
  },
  {
    slug: 'tofu-firm',
    name: 'Tofu, firm',
    kcal: 144, protein: 17, carbs: 3, fat: 9,
    units: [
      { label: 'serving', grams: 100 },
      { label: 'block', grams: 350 },
    ],
  },
  // ---- Fruit ----
  {
    slug: 'banana',
    name: 'Banana',
    kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3,
    units: [
      { label: 'medium', grams: 118 },
      { label: 'large', grams: 136 },
      { label: 'small', grams: 101 },
    ],
  },
  {
    slug: 'apple',
    name: 'Apple',
    kcal: 52, protein: 0.3, carbs: 14, fat: 0.2,
    units: [
      { label: 'medium', grams: 182 },
      { label: 'small', grams: 149 },
    ],
  },
  {
    slug: 'orange',
    name: 'Orange',
    kcal: 47, protein: 0.9, carbs: 12, fat: 0.1,
    units: [{ label: 'medium', grams: 131 }],
  },
  {
    slug: 'strawberries',
    name: 'Strawberries',
    kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3,
    units: [
      { label: 'serving', grams: 100 },
      { label: 'cup', grams: 144 },
    ],
  },
  {
    slug: 'blueberries',
    name: 'Blueberries',
    kcal: 57, protein: 0.7, carbs: 14, fat: 0.3,
    units: [
      { label: 'handful', grams: 40 },
      { label: 'cup', grams: 148 },
    ],
  },
  {
    slug: 'grapes',
    name: 'Grapes',
    kcal: 69, protein: 0.7, carbs: 18, fat: 0.2,
    units: [
      { label: 'handful', grams: 50 },
      { label: 'cup', grams: 151 },
    ],
  },
  // ---- Vegetables ----
  {
    slug: 'broccoli',
    name: 'Broccoli',
    kcal: 34, protein: 2.8, carbs: 7, fat: 0.4,
    units: [
      { label: 'serving', grams: 80 },
      { label: 'cup', grams: 91 },
    ],
  },
  {
    slug: 'carrot',
    name: 'Carrot',
    kcal: 41, protein: 0.9, carbs: 10, fat: 0.2,
    units: [{ label: 'medium', grams: 61 }],
  },
  {
    slug: 'spinach',
    name: 'Spinach',
    kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4,
    units: [
      { label: 'handful', grams: 25 },
      { label: 'cup', grams: 30 },
    ],
  },
  {
    slug: 'tomato',
    name: 'Tomato',
    kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2,
    units: [{ label: 'medium', grams: 123 }],
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1,
    units: [{ label: 'serving', grams: 100 }],
  },
  {
    slug: 'bell-pepper',
    name: 'Bell pepper',
    kcal: 31, protein: 1, carbs: 6, fat: 0.3,
    units: [{ label: 'medium', grams: 119 }],
  },
  {
    slug: 'avocado',
    name: 'Avocado',
    kcal: 160, protein: 2, carbs: 9, fat: 15,
    units: [
      { label: 'half', grams: 100 },
      { label: 'whole', grams: 200 },
    ],
  },
  // ---- Nuts, fats & misc ----
  {
    slug: 'peanut-butter',
    name: 'Peanut butter',
    kcal: 588, protein: 25, carbs: 20, fat: 50,
    units: [{ label: 'tbsp', grams: 16 }],
  },
  {
    slug: 'almonds',
    name: 'Almonds',
    kcal: 579, protein: 21, carbs: 22, fat: 50,
    units: [
      { label: 'handful', grams: 28 },
      { label: 'serving', grams: 30 },
    ],
  },
  {
    slug: 'olive-oil',
    name: 'Olive oil',
    kcal: 884, protein: 0, carbs: 0, fat: 100,
    units: [
      { label: 'tbsp', grams: 14 },
      { label: 'tsp', grams: 5 },
    ],
  },
  {
    slug: 'honey',
    name: 'Honey',
    kcal: 304, protein: 0.3, carbs: 82, fat: 0,
    units: [
      { label: 'tsp', grams: 7 },
      { label: 'tbsp', grams: 21 },
    ],
  },
  {
    slug: 'baked-beans',
    name: 'Baked beans',
    kcal: 78, protein: 4.8, carbs: 13, fat: 0.5,
    units: [
      { label: 'serving', grams: 200 },
      { label: 'half can', grams: 207 },
    ],
  },
  {
    slug: 'hummus',
    name: 'Hummus',
    kcal: 166, protein: 8, carbs: 14, fat: 10,
    units: [
      { label: 'tbsp', grams: 15 },
      { label: 'serving', grams: 50 },
    ],
  },

  // ===== Expanded set (v2) =====

  // ---- More fruit ----
  { slug: 'pear', name: 'Pear', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1,
    units: [{ label: 'medium', grams: 178 }] },
  { slug: 'peach', name: 'Peach', kcal: 39, protein: 0.9, carbs: 9.5, fat: 0.25,
    units: [{ label: 'medium', grams: 150 }] },
  { slug: 'plum', name: 'Plum', kcal: 46, protein: 0.7, carbs: 11, fat: 0.3,
    units: [{ label: 'plum', grams: 66 }] },
  { slug: 'kiwi', name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 15, fat: 0.5,
    units: [{ label: 'kiwi', grams: 69 }] },
  { slug: 'pineapple', name: 'Pineapple', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1,
    units: [{ label: 'slice', grams: 56 }, { label: 'serving', grams: 100 }] },
  { slug: 'mango', name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4,
    units: [{ label: 'serving', grams: 100 }, { label: 'half', grams: 103 }] },
  { slug: 'watermelon', name: 'Watermelon', kcal: 30, protein: 0.6, carbs: 7.6, fat: 0.15,
    units: [{ label: 'cup', grams: 152 }, { label: 'slice', grams: 280 }] },
  { slug: 'cantaloupe', name: 'Cantaloupe melon', kcal: 34, protein: 0.8, carbs: 8, fat: 0.2,
    units: [{ label: 'cup', grams: 160 }, { label: 'slice', grams: 69 }] },
  { slug: 'raspberries', name: 'Raspberries', kcal: 52, protein: 1.2, carbs: 12, fat: 0.65,
    units: [{ label: 'handful', grams: 30 }, { label: 'cup', grams: 123 }] },
  { slug: 'blackberries', name: 'Blackberries', kcal: 43, protein: 1.4, carbs: 10, fat: 0.5,
    units: [{ label: 'handful', grams: 30 }, { label: 'cup', grams: 144 }] },
  { slug: 'cherries', name: 'Cherries', kcal: 63, protein: 1.1, carbs: 16, fat: 0.2,
    units: [{ label: 'handful', grams: 50 }, { label: 'cup', grams: 154 }] },
  { slug: 'grapefruit', name: 'Grapefruit', kcal: 42, protein: 0.8, carbs: 11, fat: 0.1,
    units: [{ label: 'half', grams: 123 }] },
  { slug: 'dates-medjool', name: 'Dates, medjool', kcal: 277, protein: 1.8, carbs: 75, fat: 0.15,
    units: [{ label: 'date', grams: 24 }] },
  { slug: 'raisins', name: 'Raisins', kcal: 299, protein: 3.1, carbs: 79, fat: 0.5,
    units: [{ label: 'tbsp', grams: 9 }, { label: 'handful', grams: 30 }] },
  { slug: 'dried-apricots', name: 'Dried apricots', kcal: 241, protein: 3.4, carbs: 63, fat: 0.5,
    units: [{ label: 'apricot', grams: 8 }, { label: 'handful', grams: 40 }] },
  { slug: 'pomegranate', name: 'Pomegranate seeds', kcal: 83, protein: 1.7, carbs: 19, fat: 1.2,
    units: [{ label: 'serving', grams: 100 }, { label: 'tbsp', grams: 12 }] },

  // ---- More vegetables ----
  { slug: 'lettuce', name: 'Lettuce', kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2,
    units: [{ label: 'serving', grams: 50 }, { label: 'cup', grams: 36 }] },
  { slug: 'kale', name: 'Kale', kcal: 49, protein: 4.3, carbs: 9, fat: 0.9,
    units: [{ label: 'serving', grams: 65 }, { label: 'cup', grams: 21 }] },
  { slug: 'cabbage', name: 'Cabbage', kcal: 25, protein: 1.3, carbs: 6, fat: 0.1,
    units: [{ label: 'serving', grams: 80 }, { label: 'cup', grams: 89 }] },
  { slug: 'cauliflower', name: 'Cauliflower', kcal: 25, protein: 1.9, carbs: 5, fat: 0.3,
    units: [{ label: 'serving', grams: 80 }, { label: 'cup', grams: 100 }] },
  { slug: 'courgette', name: 'Courgette', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3,
    units: [{ label: 'medium', grams: 196 }, { label: 'serving', grams: 100 }] },
  { slug: 'mushrooms', name: 'Mushrooms', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3,
    units: [{ label: 'serving', grams: 80 }, { label: 'cup', grams: 70 }] },
  { slug: 'onion', name: 'Onion', kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1,
    units: [{ label: 'medium', grams: 110 }] },
  { slug: 'peas', name: 'Peas', kcal: 81, protein: 5.4, carbs: 14, fat: 0.4,
    units: [{ label: 'serving', grams: 80 }, { label: 'cup', grams: 145 }] },
  { slug: 'green-beans', name: 'Green beans', kcal: 31, protein: 1.8, carbs: 7, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }, { label: 'cup', grams: 125 }] },
  { slug: 'sweetcorn', name: 'Sweetcorn', kcal: 86, protein: 3.3, carbs: 19, fat: 1.4,
    units: [{ label: 'serving', grams: 80 }, { label: 'cob', grams: 90 }] },
  { slug: 'asparagus', name: 'Asparagus', kcal: 20, protein: 2.2, carbs: 3.9, fat: 0.1,
    units: [{ label: 'spear', grams: 16 }, { label: 'serving', grams: 80 }] },
  { slug: 'celery', name: 'Celery', kcal: 14, protein: 0.7, carbs: 3, fat: 0.2,
    units: [{ label: 'stick', grams: 40 }] },
  { slug: 'beetroot', name: 'Beetroot', kcal: 43, protein: 1.6, carbs: 10, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'leek', name: 'Leek', kcal: 61, protein: 1.5, carbs: 14, fat: 0.3,
    units: [{ label: 'medium', grams: 89 }] },
  { slug: 'butternut-squash', name: 'Butternut squash', kcal: 45, protein: 1, carbs: 12, fat: 0.1,
    units: [{ label: 'serving', grams: 100 }, { label: 'cup', grams: 140 }] },
  { slug: 'aubergine', name: 'Aubergine', kcal: 25, protein: 1, carbs: 6, fat: 0.2,
    units: [{ label: 'serving', grams: 100 }] },

  // ---- More proteins, meat & fish ----
  { slug: 'egg-scrambled', name: 'Scrambled eggs', kcal: 149, protein: 10, carbs: 1.6, fat: 11,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'turkey-breast', name: 'Turkey breast, cooked', kcal: 135, protein: 30, carbs: 0, fat: 1,
    units: [{ label: 'slice', grams: 30 }, { label: 'serving', grams: 100 }] },
  { slug: 'pork-chop', name: 'Pork chop, cooked', kcal: 231, protein: 26, carbs: 0, fat: 14,
    units: [{ label: 'chop', grams: 120 }] },
  { slug: 'bacon', name: 'Bacon, cooked', kcal: 541, protein: 37, carbs: 1.4, fat: 42,
    units: [{ label: 'rasher', grams: 12 }] },
  { slug: 'ham', name: 'Ham, sliced', kcal: 145, protein: 18, carbs: 1.5, fat: 7,
    units: [{ label: 'slice', grams: 28 }] },
  { slug: 'sausage-pork', name: 'Pork sausage, cooked', kcal: 297, protein: 17, carbs: 9, fat: 22,
    units: [{ label: 'sausage', grams: 50 }] },
  { slug: 'lamb', name: 'Lamb, cooked', kcal: 258, protein: 26, carbs: 0, fat: 17,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'beef-steak', name: 'Beef steak, cooked', kcal: 271, protein: 27, carbs: 0, fat: 18,
    units: [{ label: 'steak', grams: 150 }] },
  { slug: 'beef-mince-20', name: 'Beef mince, 20% fat, cooked', kcal: 254, protein: 26, carbs: 0, fat: 17,
    units: [{ label: 'serving', grams: 125 }] },
  { slug: 'beef-burger', name: 'Beef burger patty, cooked', kcal: 254, protein: 25, carbs: 0, fat: 17,
    units: [{ label: 'patty', grams: 90 }] },
  { slug: 'duck-breast', name: 'Duck breast, cooked', kcal: 337, protein: 19, carbs: 0, fat: 28,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'cod', name: 'Cod, cooked', kcal: 105, protein: 23, carbs: 0, fat: 0.9,
    units: [{ label: 'fillet', grams: 120 }] },
  { slug: 'mackerel', name: 'Mackerel, cooked', kcal: 262, protein: 24, carbs: 0, fat: 18,
    units: [{ label: 'fillet', grams: 120 }] },
  { slug: 'sardines-canned', name: 'Sardines, canned', kcal: 208, protein: 25, carbs: 0, fat: 11,
    units: [{ label: 'can', grams: 90 }, { label: 'serving', grams: 100 }] },
  { slug: 'smoked-salmon', name: 'Smoked salmon', kcal: 117, protein: 18, carbs: 0, fat: 4.3,
    units: [{ label: 'serving', grams: 50 }] },
  { slug: 'fish-fingers', name: 'Fish fingers', kcal: 200, protein: 12, carbs: 19, fat: 9,
    units: [{ label: 'finger', grams: 28 }] },

  // ---- More dairy & alternatives ----
  { slug: 'mozzarella', name: 'Mozzarella', kcal: 280, protein: 28, carbs: 3, fat: 17,
    units: [{ label: 'serving', grams: 30 }, { label: 'ball', grams: 125 }] },
  { slug: 'feta', name: 'Feta cheese', kcal: 264, protein: 14, carbs: 4, fat: 21,
    units: [{ label: 'serving', grams: 30 }] },
  { slug: 'parmesan', name: 'Parmesan', kcal: 431, protein: 38, carbs: 4, fat: 29,
    units: [{ label: 'tbsp grated', grams: 5 }, { label: 'serving', grams: 20 }] },
  { slug: 'cottage-cheese', name: 'Cottage cheese', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3,
    units: [{ label: 'serving', grams: 100 }, { label: 'pot', grams: 200 }] },
  { slug: 'cream-cheese', name: 'Cream cheese', kcal: 342, protein: 6, carbs: 4, fat: 34,
    units: [{ label: 'tbsp', grams: 15 }, { label: 'serving', grams: 30 }] },
  { slug: 'double-cream', name: 'Double cream', kcal: 449, protein: 1.7, carbs: 2.7, fat: 48,
    units: [{ label: 'tbsp', grams: 15 }] },
  { slug: 'soy-milk', name: 'Soy milk', kcal: 43, protein: 3.3, carbs: 1.8, fat: 1.8,
    units: [{ label: 'glass (200ml)', grams: 200 }] },
  { slug: 'almond-milk', name: 'Almond milk, unsweetened', kcal: 13, protein: 0.5, carbs: 0.3, fat: 1.1,
    units: [{ label: 'glass (200ml)', grams: 200 }] },
  { slug: 'oat-milk', name: 'Oat milk', kcal: 46, protein: 1, carbs: 7, fat: 1.5,
    units: [{ label: 'glass (200ml)', grams: 200 }] },
  { slug: 'ice-cream', name: 'Ice cream, vanilla', kcal: 207, protein: 3.5, carbs: 24, fat: 11,
    units: [{ label: 'scoop', grams: 65 }, { label: 'serving', grams: 100 }] },

  // ---- More grains, cereal & bread ----
  { slug: 'rice-brown-cooked', name: 'Brown rice, cooked', kcal: 123, protein: 2.7, carbs: 26, fat: 1,
    units: [{ label: 'serving', grams: 150 }, { label: 'cup', grams: 195 }] },
  { slug: 'couscous-cooked', name: 'Couscous, cooked', kcal: 112, protein: 3.8, carbs: 23, fat: 0.16,
    units: [{ label: 'serving', grams: 150 }, { label: 'cup', grams: 157 }] },
  { slug: 'quinoa-cooked', name: 'Quinoa, cooked', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9,
    units: [{ label: 'serving', grams: 150 }, { label: 'cup', grams: 185 }] },
  { slug: 'noodles-cooked', name: 'Egg noodles, cooked', kcal: 138, protein: 4.5, carbs: 25, fat: 2.1,
    units: [{ label: 'serving', grams: 150 }] },
  { slug: 'naan', name: 'Naan bread', kcal: 310, protein: 9, carbs: 50, fat: 9,
    units: [{ label: 'naan', grams: 90 }] },
  { slug: 'pitta', name: 'Pitta bread', kcal: 275, protein: 9, carbs: 55, fat: 1.2,
    units: [{ label: 'pitta', grams: 60 }] },
  { slug: 'tortilla-wrap', name: 'Tortilla wrap', kcal: 312, protein: 8, carbs: 51, fat: 8,
    units: [{ label: 'wrap', grams: 64 }] },
  { slug: 'croissant', name: 'Croissant', kcal: 406, protein: 8, carbs: 46, fat: 21,
    units: [{ label: 'croissant', grams: 57 }] },
  { slug: 'cornflakes', name: 'Cornflakes', kcal: 357, protein: 7.5, carbs: 84, fat: 0.9,
    units: [{ label: 'serving', grams: 30 }, { label: 'bowl', grams: 40 }] },
  { slug: 'weetabix', name: 'Wheat biscuits (Weetabix)', kcal: 358, protein: 12, carbs: 69, fat: 2,
    units: [{ label: 'biscuit', grams: 19 }] },
  { slug: 'muesli', name: 'Muesli', kcal: 363, protein: 10, carbs: 66, fat: 6,
    units: [{ label: 'serving', grams: 45 }] },
  { slug: 'granola', name: 'Granola', kcal: 471, protein: 10, carbs: 64, fat: 20,
    units: [{ label: 'serving', grams: 45 }] },
  { slug: 'porridge-cooked', name: 'Porridge, cooked with water', kcal: 55, protein: 2, carbs: 9, fat: 1.1,
    units: [{ label: 'bowl', grams: 220 }] },
  { slug: 'crumpet', name: 'Crumpet', kcal: 177, protein: 5.8, carbs: 36, fat: 0.9,
    units: [{ label: 'crumpet', grams: 50 }] },
  { slug: 'english-muffin', name: 'English muffin', kcal: 227, protein: 8, carbs: 44, fat: 1.8,
    units: [{ label: 'muffin', grams: 57 }] },
  { slug: 'pancake', name: 'Pancake', kcal: 227, protein: 6, carbs: 28, fat: 10,
    units: [{ label: 'pancake', grams: 40 }] },
  { slug: 'digestive', name: 'Digestive biscuit', kcal: 471, protein: 6.7, carbs: 63, fat: 21,
    units: [{ label: 'biscuit', grams: 15 }] },
  { slug: 'cream-cracker', name: 'Cream crackers', kcal: 414, protein: 9, carbs: 68, fat: 11,
    units: [{ label: 'cracker', grams: 8 }] },
  { slug: 'rice-cake', name: 'Rice cakes', kcal: 387, protein: 8, carbs: 82, fat: 3,
    units: [{ label: 'cake', grams: 9 }] },
  { slug: 'cereal-bar', name: 'Cereal bar', kcal: 380, protein: 5, carbs: 70, fat: 9,
    units: [{ label: 'bar', grams: 35 }] },

  // ---- Legumes & beans ----
  { slug: 'chickpeas', name: 'Chickpeas, canned', kcal: 139, protein: 7.3, carbs: 22, fat: 2.6,
    units: [{ label: 'serving', grams: 100 }, { label: 'half can', grams: 120 }] },
  { slug: 'kidney-beans', name: 'Kidney beans, canned', kcal: 100, protein: 6.7, carbs: 18, fat: 0.5,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'black-beans', name: 'Black beans, canned', kcal: 91, protein: 6, carbs: 16, fat: 0.3,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'lentils-cooked', name: 'Lentils, cooked', kcal: 116, protein: 9, carbs: 20, fat: 0.4,
    units: [{ label: 'serving', grams: 100 }, { label: 'cup', grams: 198 }] },
  { slug: 'butter-beans', name: 'Butter beans, canned', kcal: 92, protein: 6, carbs: 16, fat: 0.4,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'edamame', name: 'Edamame', kcal: 121, protein: 12, carbs: 9, fat: 5,
    units: [{ label: 'serving', grams: 100 }] },

  // ---- More nuts & seeds ----
  { slug: 'cashews', name: 'Cashews', kcal: 553, protein: 18, carbs: 30, fat: 44,
    units: [{ label: 'handful', grams: 30 }] },
  { slug: 'walnuts', name: 'Walnuts', kcal: 654, protein: 15, carbs: 14, fat: 65,
    units: [{ label: 'handful', grams: 28 }] },
  { slug: 'peanuts', name: 'Peanuts', kcal: 567, protein: 26, carbs: 16, fat: 49,
    units: [{ label: 'handful', grams: 30 }] },
  { slug: 'pistachios', name: 'Pistachios', kcal: 560, protein: 20, carbs: 28, fat: 45,
    units: [{ label: 'handful', grams: 30 }] },
  { slug: 'sunflower-seeds', name: 'Sunflower seeds', kcal: 584, protein: 21, carbs: 20, fat: 51,
    units: [{ label: 'tbsp', grams: 9 }, { label: 'handful', grams: 30 }] },
  { slug: 'pumpkin-seeds', name: 'Pumpkin seeds', kcal: 559, protein: 30, carbs: 11, fat: 49,
    units: [{ label: 'tbsp', grams: 10 }, { label: 'handful', grams: 30 }] },
  { slug: 'chia-seeds', name: 'Chia seeds', kcal: 486, protein: 17, carbs: 42, fat: 31,
    units: [{ label: 'tbsp', grams: 12 }] },
  { slug: 'mixed-nuts', name: 'Mixed nuts', kcal: 607, protein: 20, carbs: 21, fat: 54,
    units: [{ label: 'handful', grams: 30 }] },

  // ---- Snacks, sweets & condiments ----
  { slug: 'dark-chocolate', name: 'Dark chocolate (70%)', kcal: 598, protein: 7.8, carbs: 46, fat: 43,
    units: [{ label: 'square', grams: 10 }, { label: 'row', grams: 25 }] },
  { slug: 'milk-chocolate', name: 'Milk chocolate', kcal: 535, protein: 7.6, carbs: 59, fat: 30,
    units: [{ label: 'square', grams: 6 }, { label: 'row', grams: 25 }] },
  { slug: 'crisps', name: 'Crisps', kcal: 536, protein: 7, carbs: 53, fat: 34,
    units: [{ label: 'bag', grams: 25 }, { label: 'grab bag', grams: 35 }] },
  { slug: 'popcorn', name: 'Popcorn, popped', kcal: 387, protein: 13, carbs: 78, fat: 5,
    units: [{ label: 'serving', grams: 30 }, { label: 'bowl', grams: 50 }] },
  { slug: 'jam', name: 'Jam', kcal: 250, protein: 0.4, carbs: 62, fat: 0.1,
    units: [{ label: 'tsp', grams: 7 }, { label: 'tbsp', grams: 20 }] },
  { slug: 'choc-spread', name: 'Chocolate hazelnut spread', kcal: 539, protein: 6, carbs: 57, fat: 31,
    units: [{ label: 'tbsp', grams: 20 }] },
  { slug: 'marmite', name: 'Marmite', kcal: 269, protein: 34, carbs: 30, fat: 0.1,
    units: [{ label: 'scraping', grams: 4 }, { label: 'tsp', grams: 6 }] },
  { slug: 'mayonnaise', name: 'Mayonnaise', kcal: 680, protein: 1, carbs: 0.6, fat: 75,
    units: [{ label: 'tbsp', grams: 14 }, { label: 'tsp', grams: 5 }] },
  { slug: 'ketchup', name: 'Tomato ketchup', kcal: 102, protein: 1.2, carbs: 24, fat: 0.2,
    units: [{ label: 'tbsp', grams: 17 }, { label: 'tsp', grams: 6 }] },
  { slug: 'soy-sauce', name: 'Soy sauce', kcal: 53, protein: 8, carbs: 4.9, fat: 0.1,
    units: [{ label: 'tbsp', grams: 16 }, { label: 'tsp', grams: 5 }] },
  { slug: 'pesto', name: 'Pesto', kcal: 418, protein: 5, carbs: 6, fat: 42,
    units: [{ label: 'tbsp', grams: 16 }] },
  { slug: 'sugar', name: 'Sugar, white', kcal: 387, protein: 0, carbs: 100, fat: 0,
    units: [{ label: 'tsp', grams: 4 }, { label: 'tbsp', grams: 12 }] },
  { slug: 'maple-syrup', name: 'Maple syrup', kcal: 260, protein: 0, carbs: 67, fat: 0.1,
    units: [{ label: 'tbsp', grams: 20 }, { label: 'tsp', grams: 7 }] },
  { slug: 'vinaigrette', name: 'Vinaigrette dressing', kcal: 449, protein: 0.6, carbs: 2.5, fat: 49,
    units: [{ label: 'tbsp', grams: 15 }] },
  { slug: 'gravy', name: 'Gravy', kcal: 54, protein: 2, carbs: 6, fat: 2.5,
    units: [{ label: 'serving', grams: 70 }] },

  // ---- Drinks ----
  { slug: 'orange-juice', name: 'Orange juice', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2,
    units: [{ label: 'glass (200ml)', grams: 200 }] },
  { slug: 'apple-juice', name: 'Apple juice', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1,
    units: [{ label: 'glass (200ml)', grams: 200 }] },
  { slug: 'cola', name: 'Cola', kcal: 42, protein: 0, carbs: 11, fat: 0,
    units: [{ label: 'can (330ml)', grams: 330 }, { label: 'glass (250ml)', grams: 250 }] },
  { slug: 'cola-diet', name: 'Diet cola', kcal: 0.4, protein: 0, carbs: 0, fat: 0,
    units: [{ label: 'can (330ml)', grams: 330 }] },
  { slug: 'beer', name: 'Beer (lager)', kcal: 43, protein: 0.5, carbs: 3.6, fat: 0,
    units: [{ label: 'pint', grams: 568 }, { label: 'bottle (330ml)', grams: 330 }] },
  { slug: 'red-wine', name: 'Red wine', kcal: 85, protein: 0.1, carbs: 2.6, fat: 0,
    units: [{ label: 'glass (175ml)', grams: 175 }, { label: 'large glass (250ml)', grams: 250 }] },
  { slug: 'white-wine', name: 'White wine', kcal: 82, protein: 0.1, carbs: 2.6, fat: 0,
    units: [{ label: 'glass (175ml)', grams: 175 }, { label: 'large glass (250ml)', grams: 250 }] },
  { slug: 'latte', name: 'Latte (semi-skimmed)', kcal: 56, protein: 3, carbs: 5.3, fat: 2,
    units: [{ label: 'regular (350ml)', grams: 350 }, { label: 'small (240ml)', grams: 240 }] },
  { slug: 'smoothie', name: 'Fruit smoothie', kcal: 55, protein: 0.8, carbs: 13, fat: 0.3,
    units: [{ label: 'glass (200ml)', grams: 200 }, { label: 'bottle (250ml)', grams: 250 }] },
  { slug: 'hot-chocolate', name: 'Hot chocolate', kcal: 77, protein: 3.5, carbs: 10, fat: 2.5,
    units: [{ label: 'mug (250ml)', grams: 250 }] },

  // ---- Prepared & common meals ----
  { slug: 'pizza-cheese', name: 'Pizza, cheese & tomato', kcal: 266, protein: 11, carbs: 33, fat: 10,
    units: [{ label: 'slice', grams: 107 }] },
  { slug: 'chips', name: 'Chips / fries', kcal: 312, protein: 3.4, carbs: 41, fat: 15,
    units: [{ label: 'serving', grams: 100 }, { label: 'large portion', grams: 165 }] },
  { slug: 'baked-potato', name: 'Baked potato', kcal: 93, protein: 2.5, carbs: 21, fat: 0.1,
    units: [{ label: 'medium', grams: 173 }] },
  { slug: 'mashed-potato', name: 'Mashed potato', kcal: 108, protein: 2, carbs: 16, fat: 4.2,
    units: [{ label: 'serving', grams: 150 }] },
  { slug: 'roast-potatoes', name: 'Roast potatoes', kcal: 149, protein: 2.9, carbs: 26, fat: 4.5,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'garlic-bread', name: 'Garlic bread', kcal: 350, protein: 8, carbs: 41, fat: 17,
    units: [{ label: 'slice', grams: 40 }] },
  { slug: 'mac-cheese', name: 'Macaroni cheese', kcal: 164, protein: 6.7, carbs: 17, fat: 8,
    units: [{ label: 'serving', grams: 200 }] },
  { slug: 'vegetable-soup', name: 'Vegetable soup', kcal: 45, protein: 1.5, carbs: 7, fat: 1.3,
    units: [{ label: 'bowl', grams: 300 }] },
  { slug: 'scrambled-on-toast', name: 'Scrambled egg on toast', kcal: 199, protein: 9, carbs: 17, fat: 11,
    units: [{ label: 'serving', grams: 150 }] },

  // ---- Vegetables, third pass (the everyday gaps) ----
  { slug: 'rocket', name: 'Rocket (arugula)', kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7,
    units: [{ label: 'handful', grams: 25 }, { label: 'bag', grams: 80 }] },
  { slug: 'watercress', name: 'Watercress', kcal: 11, protein: 2.3, carbs: 1.3, fat: 0.1,
    units: [{ label: 'handful', grams: 25 }] },
  { slug: 'spring-onion', name: 'Spring onion', kcal: 32, protein: 1.8, carbs: 7.3, fat: 0.2,
    units: [{ label: 'spring onion', grams: 15 }] },
  { slug: 'shallot', name: 'Shallot', kcal: 72, protein: 2.5, carbs: 17, fat: 0.1,
    units: [{ label: 'shallot', grams: 25 }] },
  { slug: 'garlic', name: 'Garlic', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5,
    units: [{ label: 'clove', grams: 3 }, { label: 'bulb', grams: 30 }] },
  { slug: 'ginger-root', name: 'Ginger, fresh', kcal: 80, protein: 1.8, carbs: 18, fat: 0.8,
    units: [{ label: 'tsp grated', grams: 2 }, { label: 'thumb', grams: 15 }] },
  { slug: 'red-cabbage', name: 'Red cabbage', kcal: 31, protein: 1.4, carbs: 7.4, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'brussels-sprouts', name: 'Brussels sprouts', kcal: 43, protein: 3.4, carbs: 9, fat: 0.3,
    units: [{ label: 'sprout', grams: 19 }, { label: 'serving', grams: 80 }] },
  { slug: 'pak-choi', name: 'Pak choi', kcal: 13, protein: 1.5, carbs: 2.2, fat: 0.2,
    units: [{ label: 'head', grams: 116 }, { label: 'serving', grams: 80 }] },
  { slug: 'chard', name: 'Swiss chard', kcal: 19, protein: 1.8, carbs: 3.7, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'chicory', name: 'Chicory (endive)', kcal: 17, protein: 0.9, carbs: 3.4, fat: 0.1,
    units: [{ label: 'head', grams: 53 }] },
  { slug: 'kohlrabi', name: 'Kohlrabi', kcal: 27, protein: 1.7, carbs: 6.2, fat: 0.1,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'radish', name: 'Radish', kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1,
    units: [{ label: 'radish', grams: 4.5 }, { label: 'serving', grams: 60 }] },
  { slug: 'turnip', name: 'Turnip', kcal: 28, protein: 0.9, carbs: 6.4, fat: 0.1,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'swede', name: 'Swede', kcal: 37, protein: 1.1, carbs: 8.6, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'parsnip', name: 'Parsnip', kcal: 75, protein: 1.2, carbs: 18, fat: 0.3,
    units: [{ label: 'parsnip', grams: 130 }, { label: 'serving', grams: 80 }] },
  { slug: 'celeriac', name: 'Celeriac', kcal: 42, protein: 1.5, carbs: 9.2, fat: 0.3,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'fennel', name: 'Fennel bulb', kcal: 31, protein: 1.2, carbs: 7.3, fat: 0.2,
    units: [{ label: 'bulb', grams: 234 }, { label: 'serving', grams: 80 }] },
  { slug: 'artichoke', name: 'Globe artichoke, cooked', kcal: 47, protein: 2.9, carbs: 11, fat: 0.3,
    units: [{ label: 'artichoke', grams: 120 }] },
  { slug: 'pumpkin', name: 'Pumpkin', kcal: 26, protein: 1, carbs: 6.5, fat: 0.1,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'spaghetti-squash', name: 'Spaghetti squash, cooked', kcal: 31, protein: 0.6, carbs: 7, fat: 0.6,
    units: [{ label: 'cup', grams: 155 }] },
  { slug: 'okra', name: 'Okra', kcal: 33, protein: 1.9, carbs: 7.5, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'chilli-pepper', name: 'Chilli pepper, red', kcal: 40, protein: 1.9, carbs: 8.8, fat: 0.4,
    units: [{ label: 'chilli', grams: 15 }] },
  { slug: 'sugar-snap-peas', name: 'Sugar snap peas', kcal: 42, protein: 2.8, carbs: 7.5, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'mangetout', name: 'Mangetout', kcal: 42, protein: 2.8, carbs: 7.5, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'tenderstem-broccoli', name: 'Tenderstem broccoli', kcal: 35, protein: 3.1, carbs: 5.2, fat: 0.4,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'cherry-tomatoes', name: 'Cherry tomatoes', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2,
    units: [{ label: 'tomato', grams: 17 }, { label: 'serving', grams: 80 }] },
  { slug: 'chopped-tomatoes', name: 'Chopped tomatoes, tinned', kcal: 32, protein: 1.6, carbs: 7, fat: 0.3,
    units: [{ label: 'tin', grams: 400 }, { label: 'half tin', grams: 200 }] },
  { slug: 'sun-dried-tomatoes', name: 'Sun-dried tomatoes', kcal: 258, protein: 14, carbs: 56, fat: 3,
    units: [{ label: 'piece', grams: 2 }, { label: 'serving', grams: 20 }] },
  { slug: 'gherkins', name: 'Gherkins / pickles', kcal: 12, protein: 0.6, carbs: 2.3, fat: 0.2,
    units: [{ label: 'gherkin', grams: 30 }] },
  { slug: 'olives-green', name: 'Olives, green', kcal: 145, protein: 1, carbs: 3.8, fat: 15,
    units: [{ label: 'olive', grams: 4 }, { label: 'serving', grams: 30 }] },
  { slug: 'sauerkraut', name: 'Sauerkraut', kcal: 19, protein: 0.9, carbs: 4.3, fat: 0.1,
    units: [{ label: 'serving', grams: 60 }] },
  { slug: 'new-potatoes', name: 'New potatoes, boiled', kcal: 70, protein: 1.7, carbs: 16, fat: 0.1,
    units: [{ label: 'potato', grams: 45 }, { label: 'serving', grams: 150 }] },
  { slug: 'broad-beans', name: 'Broad beans', kcal: 88, protein: 7.9, carbs: 12, fat: 0.7,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'rhubarb', name: 'Rhubarb', kcal: 21, protein: 0.9, carbs: 4.5, fat: 0.2,
    units: [{ label: 'stalk', grams: 51 }, { label: 'serving', grams: 100 }] },

  // ---- Fruit, third pass ----
  { slug: 'nectarine', name: 'Nectarine', kcal: 44, protein: 1.1, carbs: 11, fat: 0.3,
    units: [{ label: 'nectarine', grams: 142 }] },
  { slug: 'apricot-fresh', name: 'Apricot, fresh', kcal: 48, protein: 1.4, carbs: 11, fat: 0.4,
    units: [{ label: 'apricot', grams: 35 }] },
  { slug: 'clementine', name: 'Clementine / satsuma', kcal: 47, protein: 0.9, carbs: 12, fat: 0.2,
    units: [{ label: 'clementine', grams: 74 }] },
  { slug: 'lemon', name: 'Lemon', kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3,
    units: [{ label: 'lemon', grams: 58 }, { label: 'juice of half', grams: 20 }] },
  { slug: 'lime', name: 'Lime', kcal: 30, protein: 0.7, carbs: 11, fat: 0.2,
    units: [{ label: 'lime', grams: 67 }] },
  { slug: 'honeydew', name: 'Honeydew melon', kcal: 36, protein: 0.5, carbs: 9.1, fat: 0.1,
    units: [{ label: 'slice', grams: 160 }, { label: 'serving', grams: 100 }] },
  { slug: 'papaya', name: 'Papaya', kcal: 43, protein: 0.5, carbs: 11, fat: 0.3,
    units: [{ label: 'serving', grams: 145 }] },
  { slug: 'passion-fruit', name: 'Passion fruit', kcal: 97, protein: 2.2, carbs: 23, fat: 0.7,
    units: [{ label: 'fruit', grams: 18 }] },
  { slug: 'fig-fresh', name: 'Fig, fresh', kcal: 74, protein: 0.8, carbs: 19, fat: 0.3,
    units: [{ label: 'fig', grams: 50 }] },
  { slug: 'figs-dried', name: 'Figs, dried', kcal: 249, protein: 3.3, carbs: 64, fat: 0.9,
    units: [{ label: 'fig', grams: 8 }, { label: 'handful', grams: 40 }] },
  { slug: 'cranberries', name: 'Cranberries, fresh', kcal: 46, protein: 0.4, carbs: 12, fat: 0.1,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'dried-cranberries', name: 'Cranberries, dried', kcal: 308, protein: 0.1, carbs: 82, fat: 1.4,
    units: [{ label: 'handful', grams: 40 }] },
  { slug: 'gooseberries', name: 'Gooseberries', kcal: 44, protein: 0.9, carbs: 10, fat: 0.6,
    units: [{ label: 'serving', grams: 100 }] },
  { slug: 'blackcurrants', name: 'Blackcurrants', kcal: 63, protein: 1.4, carbs: 15, fat: 0.4,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'redcurrants', name: 'Redcurrants', kcal: 56, protein: 1.4, carbs: 14, fat: 0.2,
    units: [{ label: 'serving', grams: 80 }] },
  { slug: 'lychee', name: 'Lychee', kcal: 66, protein: 0.8, carbs: 17, fat: 0.4,
    units: [{ label: 'lychee', grams: 10 }, { label: 'serving', grams: 80 }] },
  { slug: 'persimmon', name: 'Persimmon', kcal: 70, protein: 0.6, carbs: 19, fat: 0.2,
    units: [{ label: 'fruit', grams: 168 }] },
  { slug: 'guava', name: 'Guava', kcal: 68, protein: 2.6, carbs: 14, fat: 1,
    units: [{ label: 'guava', grams: 55 }] },
  { slug: 'coconut-fresh', name: 'Coconut, fresh', kcal: 354, protein: 3.3, carbs: 15, fat: 33,
    units: [{ label: 'serving', grams: 45 }] },
  { slug: 'prunes', name: 'Prunes', kcal: 240, protein: 2.2, carbs: 64, fat: 0.4,
    units: [{ label: 'prune', grams: 9.5 }, { label: 'handful', grams: 40 }] },
  { slug: 'sultanas', name: 'Sultanas', kcal: 302, protein: 2.5, carbs: 79, fat: 0.5,
    units: [{ label: 'handful', grams: 30 }] },
  { slug: 'plantain', name: 'Plantain', kcal: 122, protein: 1.3, carbs: 32, fat: 0.4,
    units: [{ label: 'plantain', grams: 179 }] },
  { slug: 'frozen-berries', name: 'Frozen mixed berries', kcal: 45, protein: 0.9, carbs: 9, fat: 0.4,
    units: [{ label: 'serving', grams: 80 }, { label: 'handful', grams: 50 }] },

  // ---- Bread, third pass ----
  { slug: 'sourdough', name: 'Sourdough bread', kcal: 260, protein: 10, carbs: 51, fat: 1.7,
    units: [{ label: 'slice', grams: 50 }] },
  { slug: 'rye-bread', name: 'Rye bread', kcal: 259, protein: 8.5, carbs: 48, fat: 3.3,
    units: [{ label: 'slice', grams: 32 }] },
  { slug: 'pumpernickel', name: 'Pumpernickel bread', kcal: 250, protein: 8.7, carbs: 47, fat: 3.1,
    units: [{ label: 'slice', grams: 32 }] },
  { slug: 'seeded-bread', name: 'Seeded bread', kcal: 275, protein: 10, carbs: 41, fat: 6.5,
    units: [{ label: 'slice', grams: 44 }] },
  { slug: 'granary-bread', name: 'Granary bread', kcal: 246, protein: 9.8, carbs: 43, fat: 3.1,
    units: [{ label: 'slice', grams: 40 }] },
  { slug: 'bread-brown', name: 'Brown bread', kcal: 250, protein: 9.7, carbs: 46, fat: 2.6,
    units: [{ label: 'slice', grams: 36 }] },
  { slug: 'ciabatta', name: 'Ciabatta', kcal: 271, protein: 9, carbs: 52, fat: 3,
    units: [{ label: 'roll', grams: 90 }, { label: 'slice', grams: 50 }] },
  { slug: 'baguette', name: 'Baguette', kcal: 274, protein: 9.5, carbs: 55, fat: 1.5,
    units: [{ label: 'piece', grams: 60 }, { label: 'half stick', grams: 125 }] },
  { slug: 'focaccia', name: 'Focaccia', kcal: 305, protein: 7.6, carbs: 43, fat: 11,
    units: [{ label: 'piece', grams: 70 }] },
  { slug: 'brioche', name: 'Brioche', kcal: 371, protein: 8.5, carbs: 51, fat: 15,
    units: [{ label: 'slice', grams: 35 }, { label: 'roll', grams: 50 }] },
  { slug: 'soda-bread', name: 'Soda bread', kcal: 258, protein: 7.4, carbs: 51, fat: 2.6,
    units: [{ label: 'slice', grams: 45 }] },
  { slug: 'flatbread', name: 'Flatbread', kcal: 289, protein: 8.5, carbs: 51, fat: 5.5,
    units: [{ label: 'flatbread', grams: 60 }] },
  { slug: 'chapati', name: 'Chapati / roti', kcal: 297, protein: 9, carbs: 46, fat: 8,
    units: [{ label: 'chapati', grams: 45 }] },
  { slug: 'corn-tortilla', name: 'Corn tortilla', kcal: 218, protein: 5.7, carbs: 45, fat: 2.9,
    units: [{ label: 'tortilla', grams: 26 }] },
  { slug: 'bread-roll', name: 'Bread roll, white', kcal: 274, protein: 9.5, carbs: 51, fat: 3.5,
    units: [{ label: 'roll', grams: 50 }] },
  { slug: 'burger-bun', name: 'Burger bun', kcal: 279, protein: 9.2, carbs: 50, fat: 4.3,
    units: [{ label: 'bun', grams: 60 }] },
  { slug: 'hot-dog-roll', name: 'Hot dog roll', kcal: 271, protein: 8.5, carbs: 48, fat: 4.5,
    units: [{ label: 'roll', grams: 50 }] },
  { slug: 'sandwich-thins', name: 'Sandwich thins', kcal: 240, protein: 10, carbs: 44, fat: 2.5,
    units: [{ label: 'thin', grams: 43 }] },
  { slug: 'gluten-free-bread', name: 'Gluten-free bread', kcal: 264, protein: 3.5, carbs: 46, fat: 6.5,
    units: [{ label: 'slice', grams: 30 }] },
  { slug: 'protein-bread', name: 'High-protein bread', kcal: 250, protein: 20, carbs: 22, fat: 8,
    units: [{ label: 'slice', grams: 45 }] },
  { slug: 'tea-cake', name: 'Tea cake', kcal: 297, protein: 8, carbs: 54, fat: 5.5,
    units: [{ label: 'tea cake', grams: 60 }] },
  { slug: 'hot-cross-bun', name: 'Hot cross bun', kcal: 280, protein: 7.3, carbs: 52, fat: 4.6,
    units: [{ label: 'bun', grams: 60 }] },
  { slug: 'crispbread', name: 'Crispbread (rye)', kcal: 334, protein: 9.5, carbs: 65, fat: 1.5,
    units: [{ label: 'slice', grams: 10 }] },
  { slug: 'breadsticks', name: 'Breadsticks', kcal: 412, protein: 12, carbs: 72, fat: 8,
    units: [{ label: 'stick', grams: 5 }, { label: 'pack', grams: 25 }] },
  { slug: 'croutons', name: 'Croutons', kcal: 407, protein: 12, carbs: 74, fat: 6.6,
    units: [{ label: 'handful', grams: 15 }] },
];
